import type { ReturnRow, ReturnTotal } from "@/lib/returns/types";

export interface ReturnColumn {
  key: string;
  header: string;
  type: "text" | "money" | "number" | "date" | "percent";
  currency?: string;
}

export const RETURN_COLUMNS: Record<string, ReturnColumn[]> = {
  INCOME_PRODUCTION: [
    { key: "sn", header: "S/N", type: "number" },
    { key: "date", header: "Date", type: "date" },
    { key: "trans_ref", header: "Trans. Ref.", type: "text" },
    { key: "policy_no", header: "Policy No.", type: "text" },
    { key: "endorsement", header: "Endorsement", type: "text" },
    { key: "trans_type", header: "Trans. Type", type: "text" },
    { key: "cover_from", header: "Cover From", type: "date" },
    { key: "cover_to", header: "Cover To", type: "date" },
    { key: "assured", header: "Assured", type: "text" },
    { key: "customer", header: "Customer", type: "text" },
    { key: "broker", header: "Broker/Agent", type: "text" },
    { key: "ledger_acc", header: "Ledger Acc.", type: "text" },
    { key: "sum_insured", header: "Sum Insured", type: "money" },
    { key: "gross_premium", header: "Gross Premium", type: "money" },
    { key: "brokerage", header: "Brokerage", type: "money" },
    { key: "net_premium", header: "Net Premium", type: "money" },
    { key: "tenor", header: "Tenor (days)", type: "number" },
    { key: "end_date", header: "End Date", type: "date" },
    { key: "debit_note", header: "Debit Note", type: "text" },
    { key: "credit_note", header: "Credit Note", type: "text" },
    { key: "amount_received", header: "Amount Received", type: "money" },
    { key: "date_receipt", header: "Date of Receipt", type: "date" },
    { key: "receipt_no", header: "Receipt No.", type: "text" },
    { key: "bank", header: "Bank of Lodgement", type: "text" },
    { key: "date_lodgement", header: "Date of Lodgement", type: "date" },
    { key: "remarks", header: "Remarks", type: "text" },
  ],
  PPS: [
    { key: "sn", header: "S/No", type: "number" },
    { key: "policy_no", header: "Policy No", type: "text" },
    { key: "endorsement", header: "Endorsement No", type: "text" },
    { key: "trans_type", header: "Transaction Type", type: "text" },
    { key: "cover_from", header: "From Date", type: "date" },
    { key: "cover_to", header: "To Date", type: "date" },
    { key: "assured", header: "Assured", type: "text" },
    { key: "customer", header: "Customer Name", type: "text" },
    { key: "broker", header: "Broker/Agent", type: "text" },
    { key: "sum_insured", header: "Sum Insured", type: "money" },
    { key: "gross_premium", header: "Premium", type: "money" },
    { key: "brokerage", header: "Brokerage", type: "money" },
    { key: "net_premium", header: "Net Prem", type: "money" },
    { key: "tenor", header: "Tenor (Days)", type: "number" },
    { key: "debit_note", header: "Debit Note", type: "text" },
    { key: "credit_note", header: "Credit Note No", type: "text" },
    { key: "amount_received", header: "Amount Received", type: "money" },
    { key: "date_receipt", header: "Date of Receipt", type: "date" },
    { key: "receipt_no", header: "Receipt No", type: "text" },
    { key: "bank", header: "Bank of Lodgement", type: "text" },
    { key: "date_lodgement", header: "Date of Lodgement", type: "date" },
    { key: "insurer", header: "Name of Insurer(s)", type: "text" },
    { key: "remittance", header: "Amount Remitted", type: "money" },
    { key: "unremitted", header: "Amount Unremitted", type: "money" },
    { key: "remittance_date", header: "Date Remitted", type: "date" },
    { key: "branch", header: "Branch", type: "text" },
    { key: "remarks", header: "Remarks", type: "text" },
  ],
  CRR: [
    { key: "sn", header: "S/N", type: "number" },
    { key: "date", header: "Date", type: "date" },
    { key: "policy_no", header: "Policy No.", type: "text" },
    { key: "risk_type", header: "Risk Type", type: "text" },
    { key: "client", header: "Name of Client", type: "text" },
    { key: "insurer", header: "Name of Insurer", type: "text" },
    { key: "sum_insured", header: "Sum Insured", type: "money" },
    { key: "gross_premium", header: "Gross Premium", type: "money" },
    { key: "approved_rate", header: "Approved Commission Rate", type: "percent" },
    { key: "tax_paid", header: "Tax Paid", type: "money" },
    { key: "net_rate", header: "Net Commission Rate", type: "percent" },
    { key: "brokerage_commission", header: "Brokerage Commission", type: "money" },
    { key: "other_deduction", header: "Other Deduction", type: "money" },
    { key: "net_premium", header: "Net Premium", type: "money" },
    { key: "amount_received", header: "Amount Received", type: "money" },
    { key: "receipt_no", header: "Receipt No.", type: "text" },
    { key: "remarks", header: "Remarks", type: "text" },
  ],
  BUSINESSES_GENERATED: [
    { key: "sn", header: "S/N", type: "number" },
    { key: "insured", header: "Insured", type: "text" },
    { key: "class_of_business", header: "Class of Business", type: "text" },
    { key: "insurer", header: "Insurer", type: "text" },
    { key: "gp_ngn", header: "Gross Premium (₦)", type: "money", currency: "NGN" },
    { key: "gp_usd", header: "Gross Premium ($)", type: "money", currency: "USD" },
    { key: "pc_ngn", header: "Premium Collected (₦)", type: "money", currency: "NGN" },
    { key: "pc_usd", header: "Premium Collected ($)", type: "money", currency: "USD" },
    { key: "date_collection", header: "Date of Collection", type: "date" },
    { key: "pp_ngn", header: "Premium Paid (₦)", type: "money", currency: "NGN" },
    { key: "pp_usd", header: "Premium Paid ($)", type: "money", currency: "USD" },
    { key: "date_paid", header: "Date of Premium Paid", type: "date" },
    { key: "comm_ngn", header: "Commission (₦)", type: "money", currency: "NGN" },
    { key: "comm_usd", header: "Commission ($)", type: "money", currency: "USD" },
  ],
  PERSONNEL_FIRST: [
    { key: "sn", header: "S/N", type: "number" },
    { key: "staff_name", header: "Name of Staff", type: "text" },
    { key: "staff_category", header: "Staff Category", type: "text" },
    { key: "designation", header: "Designation", type: "text" },
    { key: "gender", header: "Gender", type: "text" },
    { key: "educational_qualification", header: "Educational Qualification", type: "text" },
    { key: "professional_qualification", header: "Professional Qualification", type: "text" },
    { key: "date_of_employment", header: "Date of Employment", type: "date" },
    { key: "state_of_origin", header: "State of Origin", type: "text" },
    { key: "location", header: "Location", type: "text" },
    { key: "date_of_exit", header: "Date of Exit", type: "date" },
    { key: "reason_for_leaving", header: "Reasons for Leaving", type: "text" },
  ],
  PERSONNEL_SECOND: [
    { key: "category", header: "Category of Staff", type: "text" },
    { key: "previous", header: "Previous Number Total", type: "number" },
    { key: "entry", header: "Total Entry in Period", type: "number" },
    { key: "exit", header: "Total Exit in Period", type: "number" },
    { key: "current", header: "Current Number", type: "number" },
  ],
  FORM_1C: [
    { key: "item", header: "Item", type: "number" },
    { key: "insurer", header: "Insurer", type: "text" },
    { key: "gross_premium", header: "Gross Premium", type: "money" },
    { key: "collected", header: "Premium Collected", type: "money" },
    { key: "paid", header: "Premium Paid to Insurer", type: "money" },
    { key: "commission", header: "Commission", type: "money" },
  ],
  BROKERAGE_COMMISSION: [
    { key: "sn", header: "S/N", type: "number" },
    { key: "client", header: "Name of Client", type: "text" },
    { key: "insurer", header: "Name of Insurer", type: "text" },
    { key: "policy_no", header: "Policy No.", type: "text" },
    { key: "class_of_business", header: "Class of Business", type: "text" },
    { key: "date", header: "Date of Policy", type: "date" },
    { key: "sum_insured", header: "Sum Insured", type: "money" },
    { key: "gross_premium", header: "Gross Premium", type: "money" },
    { key: "commission_rate", header: "Commission Rate", type: "percent" },
    { key: "commission_earned", header: "Commission Earned", type: "money" },
    { key: "withholding_tax", header: "Withholding Tax (WHT)", type: "money" },
    { key: "net_commission", header: "Net Commission Received", type: "money" },
    { key: "date_received", header: "Date Commission Received", type: "date" },
    { key: "receipt_no", header: "Receipt No.", type: "text" },
    { key: "remarks", header: "Remarks", type: "text" },
  ],
  NEW_POLICIES: [
    { key: "sn", header: "S/N", type: "number" },
    { key: "policy_no", header: "Policy No.", type: "text" },
    { key: "trans_ref", header: "Trans. Ref.", type: "text" },
    { key: "transaction_date", header: "Transaction Date", type: "date" },
    { key: "client", header: "Name of Client", type: "text" },
    { key: "insured", header: "Name of Insured", type: "text" },
    { key: "insurer", header: "Name of Insurer", type: "text" },
    { key: "class_of_business", header: "Class of Business", type: "text" },
    { key: "risk_type", header: "Risk Type", type: "text" },
    { key: "sum_insured", header: "Sum Insured", type: "money" },
    { key: "gross_premium", header: "Gross Premium", type: "money" },
    { key: "premium_collected", header: "Premium Collected", type: "money" },
    { key: "premium_paid_to_insurer", header: "Premium Paid to Insurer", type: "money" },
    { key: "brokerage_commission", header: "Commission", type: "money" },
    { key: "tax", header: "Withholding Tax", type: "money" },
    { key: "net_premium", header: "Net Premium", type: "money" },
    { key: "premium_due_date", header: "Premium Due Date", type: "date" },
    { key: "cover_from", header: "Cover From", type: "date" },
    { key: "cover_to", header: "Cover To", type: "date" },
    { key: "renewal_due_date", header: "Renewal Due Date", type: "date" },
    { key: "premium_collection_date", header: "Premium Collection Date", type: "date" },
    { key: "premium_payment_date", header: "Premium Payment Date", type: "date" },
    { key: "receipt_no", header: "Receipt No.", type: "text" },
    { key: "bank", header: "Bank of Lodgement", type: "text" },
    { key: "currency", header: "Currency", type: "text" },
    { key: "branch", header: "Branch Location", type: "text" },
    { key: "remarks", header: "Remarks", type: "text" },
  ],
  RENEWAL_POLICIES: [
    { key: "sn", header: "S/N", type: "number" },
    { key: "policy_no", header: "Policy No.", type: "text" },
    { key: "trans_ref", header: "Trans. Ref.", type: "text" },
    { key: "transaction_date", header: "Transaction Date", type: "date" },
    { key: "client", header: "Name of Client", type: "text" },
    { key: "insured", header: "Name of Insured", type: "text" },
    { key: "insurer", header: "Name of Insurer", type: "text" },
    { key: "class_of_business", header: "Class of Business", type: "text" },
    { key: "risk_type", header: "Risk Type", type: "text" },
    { key: "sum_insured", header: "Sum Insured", type: "money" },
    { key: "gross_premium", header: "Gross Premium", type: "money" },
    { key: "premium_collected", header: "Premium Collected", type: "money" },
    { key: "premium_paid_to_insurer", header: "Premium Paid to Insurer", type: "money" },
    { key: "brokerage_commission", header: "Commission", type: "money" },
    { key: "tax", header: "Withholding Tax", type: "money" },
    { key: "net_premium", header: "Net Premium", type: "money" },
    { key: "premium_due_date", header: "Premium Due Date", type: "date" },
    { key: "cover_from", header: "Cover From", type: "date" },
    { key: "cover_to", header: "Cover To", type: "date" },
    { key: "renewal_due_date", header: "Renewal Due Date", type: "date" },
    { key: "premium_collection_date", header: "Premium Collection Date", type: "date" },
    { key: "premium_payment_date", header: "Premium Payment Date", type: "date" },
    { key: "receipt_no", header: "Receipt No.", type: "text" },
    { key: "bank", header: "Bank of Lodgement", type: "text" },
    { key: "currency", header: "Currency", type: "text" },
    { key: "branch", header: "Branch Location", type: "text" },
    { key: "remarks", header: "Remarks", type: "text" },
  ],
  FORM_7_2B: [
    { key: "month", header: "MONTH", type: "text" },
    { key: "sn", header: "S/N", type: "number" },
    { key: "name_of_insured", header: "NAME OF INSURED/POLICY NO.", type: "text" },
    { key: "insurer", header: "NAME OF INSURER", type: "text" },
    { key: "sd", header: "COVER START DATE", type: "date" },
    { key: "ed", header: "COVER END DATE", type: "date" },
    { key: "sum_insured", header: "SUM INSURED", type: "money" },
    { key: "premium_paid_directly", header: "(a) PREMIUM PAID DIRECTLY TO INSURERS", type: "money" },
    { key: "premium_paid_to_brokers_local", header: "(b) PREMIUM PAID TO BROKERS (LOCAL)", type: "money" },
    { key: "premium_paid_to_brokers_foreign", header: "(c) PREMIUM PAID TO BROKERS (FOREIGN)", type: "money" },
    { key: "total_gross_premium", header: "(d) TOTAL GROSS PREMIUM", type: "money" },
    { key: "net_premium", header: "(e) NET PREMIUM", type: "money" },
    { key: "clients_bank", header: "PREMIUM IN CLIENTS' BANK A/C OR CHEQUE OR CASH", type: "money" },
    { key: "date_received", header: "DATE PREMIUM/CLAIMS RECEIVED", type: "date" },
    { key: "premium_received_by_broker", header: "PREMIUM RECEIVED BY BROKER FROM INSURED", type: "money" },
    { key: "total_commission_fee", header: "TOTAL COMMISSION FEE INCOME", type: "money" },
    { key: "commission_due_to_cobrokers", header: "COMMISSION DUE TO CO-BROKERS", type: "money" },
    { key: "commission_due_to_reporting", header: "COMMISSION DUE TO REPORTING BROKERS", type: "money" },
    { key: "commission_income_earned", header: "COMMISSION INCOME EARNED", type: "money" },
    { key: "deferred_commission", header: "DEFERRED COMMISSION INCOME", type: "money" },
  ],
  FORM_7_2C: [
    { key: "month", header: "MONTH", type: "text" },
    { key: "sn", header: "S/N", type: "number" },
    { key: "name_of_insured", header: "NAME OF INSURED/POLICY NO.", type: "text" },
    { key: "insurer", header: "NAME OF INSURER", type: "text" },
    { key: "sd", header: "COVER START DATE", type: "date" },
    { key: "ed", header: "COVER END DATE", type: "date" },
    { key: "total_received", header: "(a) TOTAL PREMIUM/CLAIMS RECEIVED BY THE BROKERS", type: "money" },
    { key: "premium_due_to_insurers", header: "(b) PREMIUM DUE TO INSURERS (NET OF VAT)", type: "money" },
    { key: "deposit_by_insured", header: "(c′) DEPOSIT MADE INTO CLIENTS' ACCOUNT BY INSURED", type: "money" },
    { key: "returned_premium_due", header: "(d) RETURNED PREMIUM DUE TO INSURED", type: "money" },
    { key: "claims_due", header: "(e′) CLAIMS DUE TO INSURED", type: "money" },
    { key: "vat_due", header: "(f) VAT DUE TO FIRS/SIRS", type: "money" },
    { key: "commission_due_cobrokers", header: "(g) COMMISSION DUE TO CO-BROKER(S)", type: "money" },
    { key: "commission_due_reporting", header: "(h) COMMISSION DUE TO REPORTING BROKER", type: "money" },
    { key: "date_remitted", header: "DATE PREMIUM/CLAIMS/VAT/COMMISSION REMITTED", type: "date" },
    { key: "paying_bank", header: "CLIENTS' ACCOUNT PAYING BANK", type: "text" },
    { key: "premium_remitted", header: "(i) PREMIUM REMITTED TO INSURERS", type: "money" },
    { key: "claims_remitted", header: "(j) CLAIMS/RETURNED PREMIUM/DEPOSIT REMITTED TO INSURED", type: "money" },
    { key: "vat_remitted", header: "(k) VAT REMITTED TO FIRS/SIRS", type: "money" },
    { key: "commission_remitted", header: "(L) COMMISSION REMITTED TO CO-BROKERS & REPORTING BROKER", type: "money" },
    { key: "outstanding_premium", header: "(m) OUTSTANDING PREMIUM DUE TO INSURERS", type: "money" },
    { key: "outstanding_claims", header: "(n) OUTSTANDING CLAIMS/RETURNED PREMIUM/DEPOSIT DUE TO INSURED", type: "money" },
    { key: "outstanding_vat", header: "(o) OUTSTANDING VAT DUE TO FIRS/SIRS", type: "money" },
    { key: "outstanding_commission", header: "(p) OUTSTANDING COMMISSION DUE TO CO-BROKERS & REPORTING BROKER", type: "money" },
  ],
  CLAIMS_AWAITING: [
    { key: "sn", header: "S/N", type: "number" },
    { key: "date_notified_by_insured", header: "Date of Claim Notification by Insured", type: "date" },
    { key: "date_notified_to_insurer", header: "Date of Claim Notification to Insurer", type: "date" },
    { key: "insurer_name", header: "Name of Insurer", type: "text" },
    { key: "claim_no", header: "Claim No.", type: "text" },
    { key: "claim_amount", header: "Claim Amount", type: "money" },
    { key: "date_discharge_voucher", header: "Date of Receipt of Discharge Voucher", type: "date" },
    { key: "insured_beneficiary", header: "Name of Insured/Beneficiary", type: "text" },
    { key: "date_payment", header: "Date of Payment by Insurer", type: "text" },
  ],
  BIZ_SCHEDULE: [
    { key: "sn", header: "S/N", type: "number" },
    { key: "insured_name", header: "Name of Insured", type: "text" },
    { key: "insurer_name", header: "Name of Insurer", type: "text" },
    { key: "policy_no", header: "Policy No.", type: "text" },
    { key: "policy_detail", header: "Policy Detail", type: "text" },
    { key: "commencement_of_risk", header: "Commencement of Risk", type: "date" },
    { key: "sum_insured", header: "Sum Insured", type: "money" },
    { key: "premium_local", header: "Premium (Local)", type: "money", currency: "NGN" },
    { key: "premium_foreign", header: "Premium (Foreign)", type: "money", currency: "USD" },
    { key: "date_received", header: "Date of Receipt of Premium", type: "date" },
    { key: "date_transmitted", header: "Date of Transmission of Premium", type: "date" },
    { key: "commission_local", header: "Commission (Local)", type: "money", currency: "NGN" },
    { key: "commission_foreign", header: "Commission (Foreign)", type: "money", currency: "USD" },
  ],
};

const TOTAL_DEFS: Record<string, { label: string; key: string; currency?: string }[]> = {
  INCOME_PRODUCTION: [
    { label: "Sum insured", key: "sum_insured" },
    { label: "Gross premium", key: "gross_premium" },
    { label: "Brokerage", key: "brokerage" },
    { label: "Net premium", key: "net_premium" },
    { label: "Amount received", key: "amount_received" },
  ],
  PPS: [
    { label: "Sum insured", key: "sum_insured" },
    { label: "Premium", key: "gross_premium" },
    { label: "Brokerage", key: "brokerage" },
    { label: "Net prem", key: "net_premium" },
    { label: "Amount received", key: "amount_received" },
  ],
  CRR: [
    { label: "Sum insured", key: "sum_insured" },
    { label: "Gross premium", key: "gross_premium" },
    { label: "Tax paid", key: "tax_paid" },
    { label: "Brokerage commission", key: "brokerage_commission" },
    { label: "Other deduction", key: "other_deduction" },
    { label: "Net premium", key: "net_premium" },
    { label: "Amount received", key: "amount_received" },
  ],
  BUSINESSES_GENERATED: [
    { label: "Gross premium (₦)", key: "gp_ngn", currency: "NGN" },
    { label: "Gross premium ($)", key: "gp_usd", currency: "USD" },
    { label: "Premium collected (₦)", key: "pc_ngn", currency: "NGN" },
    { label: "Premium collected ($)", key: "pc_usd", currency: "USD" },
    { label: "Premium paid (₦)", key: "pp_ngn", currency: "NGN" },
    { label: "Premium paid ($)", key: "pp_usd", currency: "USD" },
    { label: "Commission (₦)", key: "comm_ngn", currency: "NGN" },
    { label: "Commission ($)", key: "comm_usd", currency: "USD" },
  ],
  FORM_1C: [
    { label: "Gross premium", key: "gross_premium" },
    { label: "Premium collected", key: "collected" },
    { label: "Premium paid to insurer", key: "paid" },
    { label: "Commission", key: "commission" },
  ],
  BROKERAGE_COMMISSION: [
    { label: "Sum insured", key: "sum_insured" },
    { label: "Gross premium", key: "gross_premium" },
    { label: "Commission earned", key: "commission_earned" },
    { label: "Withholding tax (WHT)", key: "withholding_tax" },
    { label: "Net commission received", key: "net_commission" },
  ],
  NEW_POLICIES: [
    { label: "Sum insured", key: "sum_insured" },
    { label: "Gross premium", key: "gross_premium" },
    { label: "Premium collected", key: "premium_collected" },
    { label: "Premium paid to insurer", key: "premium_paid_to_insurer" },
    { label: "Commission", key: "brokerage_commission" },
    { label: "Withholding tax", key: "tax" },
    { label: "Net premium", key: "net_premium" },
  ],
  RENEWAL_POLICIES: [
    { label: "Sum insured", key: "sum_insured" },
    { label: "Gross premium", key: "gross_premium" },
    { label: "Premium collected", key: "premium_collected" },
    { label: "Premium paid to insurer", key: "premium_paid_to_insurer" },
    { label: "Commission", key: "brokerage_commission" },
    { label: "Withholding tax", key: "tax" },
    { label: "Net premium", key: "net_premium" },
  ],
  FORM_7_2B: [
    { label: "Sum insured", key: "sum_insured" },
    { label: "Total gross premium (d)", key: "total_gross_premium" },
    { label: "Net premium (e)", key: "net_premium" },
    { label: "Premium received by broker", key: "premium_received_by_broker" },
    { label: "Total commission fee income", key: "total_commission_fee" },
    { label: "Commission due to co-brokers", key: "commission_due_to_cobrokers" },
    { label: "Commission due to reporting brokers", key: "commission_due_to_reporting" },
    { label: "Commission income earned", key: "commission_income_earned" },
    { label: "Deferred commission income", key: "deferred_commission" },
  ],
  FORM_7_2C: [
    { label: "Total premium received by brokers", key: "total_received" },
    { label: "Premium due to insurers", key: "premium_due_to_insurers" },
    { label: "Commission due to reporting broker", key: "commission_due_reporting" },
    { label: "Premium remitted to insurers", key: "premium_remitted" },
    { label: "Commission remitted", key: "commission_remitted" },
    { label: "Outstanding premium due to insurers", key: "outstanding_premium" },
    { label: "Outstanding commission due", key: "outstanding_commission" },
  ],
  CLAIMS_AWAITING: [
    { label: "Claim amount", key: "claim_amount" },
  ],
  BIZ_SCHEDULE: [
    { label: "Sum insured", key: "sum_insured" },
    { label: "Premium (local)", key: "premium_local" },
    { label: "Premium (foreign)", key: "premium_foreign" },
    { label: "Commission (local)", key: "commission_local" },
    { label: "Commission (foreign)", key: "commission_foreign" },
  ],
};

export function computeReturnTotals(code: string, rows: ReturnRow[]): ReturnTotal[] {
  const defs = TOTAL_DEFS[code];
  if (!defs) return [];

  if (code === "PERSONNEL") {
    const firstCount = rows.filter((r) => r.schedule === "FIRST").length;
    const totalRow = rows.find((r) => r.schedule === "SECOND" && r.category === "TOTAL");
    const totals: ReturnTotal[] = [{ label: "Staff on roll in period", value: firstCount }];
    if (totalRow) {
      totals.push(
        { label: "Previous number", value: Number(totalRow.previous) },
        { label: "Total entry in period", value: Number(totalRow.entry) },
        { label: "Total exit in period", value: Number(totalRow.exit) },
        { label: "Current number", value: Number(totalRow.current) }
      );
    }
    return totals;
  }

  return defs.map((d) => ({
    label: d.label,
    value: round2(rows.reduce((sum, r) => sum + (Number(r[d.key]) || 0), 0)),
    currency: d.currency,
  }));
}

function round2(value: number): number {
  return Math.round((value + Number.EPSILON) * 100) / 100;
}
